### ISSUE TITLE
Update query.

### ISSUE THREAD

**Issue by heyitsbench** [heyitsbench/blizzlike-teles#1]
More macros have been sent over time than just vanilla. These can be found in ~~[this ZIP folder](https://github.com/heyitsbench/blizzlike-teles/files/12836011/WoW-0.2.0.10026-to-0.2.0.10048-enUS-patch.zip)~~. This query should be updated with these updated worldport locations.

Edit: [Here is an updated ZIP folder with all macros from PTR clients where found.](https://github.com/heyitsbench/blizzlike-teles/files/13029261/WTF.zip)
Edit edit: [Here is an additional ZIP with all macros condensed to one directory.](https://github.com/heyitsbench/blizzlike-teles/files/13029319/WTF.zip)

**Comment by Kitzunu** [comment]
u suck

**Comment by heyitsbench** [comment]
I have noticed that a few macros changed between PTR builds. I did a diff of the various directories in the ZIP and have made a gist of the differing files [here](https://gist.github.com/heyitsbench/454e4e0f22b06d28f22f63fef25a4c93).
